# Generated by Django 5.2.12 on 2026-04-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="heatmap_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
