# Generated by Django 5.2.12 on 2026-04-04 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0003_analysisresult_heatmap_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video"), ("audio", "Audio")],
                max_length=10,
            ),
        ),
    ]
