# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xd8bfpC53JwvSGBrBjdtEoDiaAl0NKq7
"""

from google.colab import drive
drive.mount('/content/drive')

import os

BASE_PATH = "/content/drive/MyDrive/deepx_project"  # change if needed

DATA_PATH = os.path.join(BASE_PATH, "data")
MODEL_PATH = os.path.join(BASE_PATH, "models")

import os

print(os.listdir("/content/drive/MyDrive"))

import zipfile
import os

zip_path = "/content/drive/MyDrive/DeepFake Detection.zip"
extract_path = "/content/drive/MyDrive/deepx_project/data"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzipped successfully!")

print(os.listdir("/content/drive/MyDrive/deepx_project/data"))

base = "/content/drive/MyDrive/deepx_project/data/Bangla Audio Dataset Original and DeepFake Voices for AI-Based Voice Analysis and Detection"

print(os.listdir(base))

base = "/content/drive/MyDrive/deepx_project/data/Bangla Audio Dataset Original and DeepFake Voices for AI-Based Voice Analysis and Detection/Dataset"

print(os.listdir(base))

import zipfile
import os

zip_path = "/content/drive/MyDrive/DeepFake Detection.zip"
extract_path = "/content/drive/MyDrive/deepx_project/main_data"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzipped main dataset!")

print(os.listdir("/content/drive/MyDrive/deepx_project/main_data"))

import zipfile

zip_path = "/content/drive/MyDrive/DeepFake Detection.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    print(zip_ref.namelist()[:20])  # show first 20 files

!unzip -q "/content/drive/MyDrive/LA.zip" -d "/content/LA_data"

import os
print(os.listdir("/content/LA_data"))

import os
print(os.listdir("/content/LA_data/LA"))

protocol_path = "/content/LA_data/LA/ASVspoof2019_LA_cm_protocols"

import os
print(os.listdir(protocol_path))

import librosa
import numpy as np
import os
from tqdm import tqdm

X_train = []
y_train = []

train_protocol = "/content/LA_data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"
train_audio_path = "/content/LA_data/LA/ASVspoof2019_LA_train/flac"

with open(train_protocol, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines):
    parts = line.strip().split()

    file_id = parts[1]
    label = parts[-1]

    file_path = os.path.join(train_audio_path, file_id + ".flac")

    try:
        audio, sr = librosa.load(file_path, sr=None, duration=3)

        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
        mfcc_scaled = np.mean(mfcc.T, axis=0)

        X_train.append(mfcc_scaled)
        y_train.append(0 if label == "bonafide" else 1)

    except:
        continue

X_train = np.array(X_train)
y_train = np.array(y_train)

print("Train shape:", X_train.shape)

import numpy as np

np.save("/content/drive/MyDrive/deepx_project/X.npy", X)
np.save("/content/drive/MyDrive/deepx_project/y.npy", y)

from sklearn.utils import shuffle

X, y = shuffle(X, y, random_state=42)

from sklearn.preprocessing import StandardScaler
import joblib

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)

joblib.dump(scaler, "/content/drive/MyDrive/deepx_project/scaler.pkl")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(128, activation='relu', input_shape=(40,)),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(1, activation='sigmoid')
])

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0003),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive"))

print(os.listdir("/content/drive/MyDrive/deepx_project"))

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive"))

import numpy as np

X = np.load("/content/drive/MyDrive/deepx_project/X.npy")
y = np.load("/content/drive/MyDrive/deepx_project/y.npy")

print(X.shape)

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

import joblib

scaler = joblib.load("/content/drive/MyDrive/deepx_project/scaler.pkl")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(128, activation='relu', input_shape=(40,)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10)

model.save("/content/drive/MyDrive/deepx_project/final_model.h5")

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.models import load_model
import joblib

model = load_model("/content/drive/MyDrive/deepx_project/final_model.h5")
scaler = joblib.load("/content/drive/MyDrive/deepx_project/scaler.pkl")

print("✅ Model and scaler loaded")

import librosa
import numpy as np

def extract_features(file_path):

    audio, sr = librosa.load(file_path, sr=16000, duration=3)

    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
    delta = librosa.feature.delta(mfcc)
    delta2 = librosa.feature.delta(mfcc, order=2)

    features = np.hstack([
        np.mean(mfcc.T, axis=0),
        np.mean(delta.T, axis=0),
        np.mean(delta2.T, axis=0)
    ])

    return features

def predict_audio(file_path):
    file_path = convert_to_wav(file_path)

    features = extract_features(file_path)
    features = scaler.transform([features])

    prediction = model.predict(features)[0][0]

    print("Raw score:", prediction)

    if prediction > 0.7:   # increased threshold
        return "🔴 Fake Voice"
    else:
        return "🟢 Real Voice"

from pydub import AudioSegment

def convert_to_wav(file_path):
    audio = AudioSegment.from_file(file_path)
    wav_path = "temp.wav"
    audio.export(wav_path, format="wav")
    return wav_path


def predict_audio(file_path):
    file_path = convert_to_wav(file_path)

    features = extract_features(file_path)
    features = scaler.transform([features])

    prediction = model.predict(features)[0][0]

    print("Raw score:", prediction)

    if prediction > 0.7:
        return "🔴 Fake Voice"
    else:
        return "🟢 Real Voice"

import librosa
import numpy as np

def extract_features(file_path):
    audio, sr = librosa.load(file_path, sr=16000, duration=3)

    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
    delta = librosa.feature.delta(mfcc)
    delta2 = librosa.feature.delta(mfcc, order=2)

    features = np.hstack([
        np.mean(mfcc.T, axis=0),
        np.mean(delta.T, axis=0),
        np.mean(delta2.T, axis=0)
    ])

    return features

import os
print(os.listdir("/content"))

!unzip -q "/content/drive/MyDrive/LA.zip" -d "/content/LA_data"

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
print(os.listdir("/content/drive/MyDrive"))

!unzip -q "/content/drive/MyDrive/LA.zip" -d "/content/LA_data"

print(os.listdir("/content/LA_data/LA"))

import os
import numpy as np
from tqdm import tqdm

X = []
y = []

# Paths
train_protocol = "/content/LA_data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"
train_audio_path = "/content/LA_data/LA/ASVspoof2019_LA_train/flac"

print("Processing TRAIN dataset...")

with open(train_protocol, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines):
    parts = line.strip().split()

    file_id = parts[1]
    label = parts[-1]

    file_path = os.path.join(train_audio_path, file_id + ".flac")

    try:
        # ✅ NEW FEATURE EXTRACTION (REPLACED LINE)
        features = extract_features(file_path)

        X.append(features)
        y.append(0 if label == "bonafide" else 1)

    except Exception as e:
        continue

X = np.array(X)
y = np.array(y)

print("Dataset shape:", X.shape)

import os
print(os.listdir("/content/LA_data/LA/ASVspoof2019_LA_train"))

print(os.listdir("/content/LA_data/LA/ASVspoof2019_LA_train/flac")[:5])

!apt-get install -y libsndfile1

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!unzip -qo "/content/drive/MyDrive/LA.zip" -d "/content/LA_data"

import librosa
import numpy as np
import os

# Test one file
sample_dir = "/content/LA_data/LA/ASVspoof2019_LA_train/flac/"
sample_file = os.path.join(sample_dir, os.listdir(sample_dir)[0])

try:
    audio, sr = librosa.load(sample_file, sr=16000)
    # Assuming your extract_features function is defined, test it:
    features = extract_features(sample_file)
    print(f"Success! File: {sample_file}")
    print(f"Features Shape: {features.shape}")
except Exception as e:
    print(f"Still failing! Error: {e}")

import librosa
import numpy as np

def extract_features(file_path):
    """
    Extracts MFCC features from an audio file.
    Adjust 'n_mfcc' if your project requires a specific number (like 20, 40, or 60).
    """
    try:
        # Load audio (16k Hz is standard for ASVspoof)
        audio, sr = librosa.load(file_path, sr=16000)

        # Extract MFCCs
        mfccs = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)

        # Take the mean across time so we get a fixed-size vector
        mfccs_processed = np.mean(mfccs.T, axis=0)

        return mfccs_processed
    except Exception as e:
        print(f"Error extracting {file_path}: {e}")
        return None

import os

sample_dir = "/content/LA_data/LA/ASVspoof2019_LA_train/flac/"
files = [f for f in os.listdir(sample_dir) if f.endswith('.flac')]
sample_file = os.path.join(sample_dir, files[0])

features = extract_features(sample_file)

if features is not None:
    print("✅ Success!")
    print(f"Feature shape: {features.shape}")
else:
    print("❌ Extraction failed.")

import librosa
import numpy as np

def extract_features(file_path):
    try:
        # 1. Load audio
        audio, sr = librosa.load(file_path, sr=16000)

        # 2. Extract Base MFCCs (40)
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)

        # 3. Calculate Delta (40) and Delta-Delta (40)
        delta = librosa.feature.delta(mfcc)
        delta2 = librosa.feature.delta(mfcc, order=2)

        # 4. Stack them vertically: (120, time_steps)
        combined = np.concatenate((mfcc, delta, delta2), axis=0)

        # 5. Pool across time (Average) to get a flat vector of (120,)
        features_processed = np.mean(combined.T, axis=0)

        return features_processed
    except Exception as e:
        print(f"Error extracting {file_path}: {e}")
        return None

# Test one file again
test_feat = extract_features(sample_file)
print(f"New Feature Shape: {test_feat.shape}")
# Target: (120,)

!find /content/LA_data -name "ASVspoof2019.LA.cm.train.trl.txt"

import os

def list_files(startpath):
    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)
        # Only show first 3 files in each folder so it doesn't spam
        for f in files[:3]:
            print('{}{}'.format(subindent, f))

list_files('/content/LA_data')

import os

# Updated to match your exact folder structure
protocol_path = "/content/LA_data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"
sample_dir = "/content/LA_data/LA/ASVspoof2019_LA_train/flac/"

train_protocols = []

if os.path.exists(protocol_path):
    with open(protocol_path, 'r') as f:
        for line in f:
            parts = line.strip().split(' ')
            if len(parts) >= 5:
                # parts[1] is filename, parts[4] is 'bonafide' or 'spoof'
                train_protocols.append([parts[1], parts[4]])
    print(f"✅ Success! Loaded {len(train_protocols)} protocols.")
else:
    print(f"❌ Path still not found! Please check: {protocol_path}")

import numpy as np

X = []
y = []

print("Starting extraction... this will take some time.")

for i, (file_name, label) in enumerate(train_protocols):
    file_path = os.path.join(sample_dir, file_name + ".flac")

    # Use the extract_features function we defined earlier (the 120-feature one)
    features = extract_features(file_path)

    if features is not None:
        X.append(features)
        y.append(1 if label == 'bonafide' else 0)

    # Progress bar every 2000 files
    if i % 2000 == 0:
        print(f"Processed {i}/{len(train_protocols)} files...")

X = np.array(X)
y = np.array(y)

print("--- FINISHED ---")
print(f"Final X shape: {X.shape}") # Should be (25380, 120)
print(f"Final y shape: {y.shape}")

# Save to your project folder
save_path_X = "/content/drive/MyDrive/deepx_project/X_new.npy"
save_path_y = "/content/drive/MyDrive/deepx_project/y_new.npy"

# Create directory if it doesn't exist
!mkdir -p /content/drive/MyDrive/deepx_project/

np.save(save_path_X, X)
np.save(save_path_y, y)

print(f"🚀 Data safely backed up to Drive at {save_path_X}")

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Only run these loads if you restarted your session:
# X = np.load("/content/drive/MyDrive/deepx_project/X_new.npy")
# y = np.load("/content/drive/MyDrive/deepx_project/y_new.npy")

# Split into Training (80%) and Validation (20%)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Training set: {X_train.shape}")
print(f"Validation set: {X_val.shape}")

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)

# Optional: Save the scaler so you can use it for "Evaluation" later
import joblib
joblib.dump(scaler, "/content/drive/MyDrive/deepx_project/scaler.pkl")

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(120,)),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid') # Binary output: 1 for Bonafide, 0 for Spoof
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_val, y_val),
    verbose=1
)

model.save("/content/drive/MyDrive/deepx_project/asv_spoof_model.h5")
print("Model saved to Drive! 🏆")

import matplotlib.pyplot as plt

# Plot Accuracy
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Model Accuracy')
plt.legend()
plt.show()

# Plot Loss
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Model Loss')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# Get predictions
y_pred = (model.predict(X_val) > 0.5).astype("int32")

# Generate Matrix
cm = confusion_matrix(y_val, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Spoof', 'Bonafide'], yticklabels=['Spoof', 'Bonafide'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

print(classification_report(y_val, y_pred))

def predict_audio(file_path):
    # 1. Extract features using the function we built earlier
    features = extract_features(file_path)
    if features is None:
        return "Error processing file"

    # 2. Scale features (using the scaler we fit earlier)
    features_scaled = scaler.transform(features.reshape(1, -1))

    # 3. Predict
    prediction = model.predict(features_scaled)

    # 4. Result
    label = "BONAFIDE (HUMAN)" if prediction[0][0] > 0.5 else "SPOOF (AI/ROBOT)"
    confidence = prediction[0][0] if prediction[0][0] > 0.5 else 1 - prediction[0][0]

    return f"Result: {label} ({confidence*100:.2f}% confidence)"

# Test it on a random file from your eval or dev folder!
test_file = "/content/LA_data/LA/ASVspoof2019_LA_dev/flac/LA_D_7603562.flac"
print(predict_audio(test_file))

from scipy.optimize import brentq
from scipy.interpolate import interp1d
from sklearn.metrics import roc_curve

# 1. Get raw probability scores (not 0 or 1, but the decimal)
y_scores = model.predict(X_val).ravel()

# 2. Calculate ROC curve
fpr, tpr, thresholds = roc_curve(y_val, y_scores, pos_label=1)

# 3. Find the EER
eer = brentq(lambda x : 1. - x - interp1d(fpr, tpr)(x), 0., 1.)
print(f"✅ Your Model EER: {eer * 100:.4f}%")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Final Evaluation
y_pred_final = (model.predict(X_val) > 0.5).astype("int32")

print("--- FINAL MODEL PERFORMANCE ---")
print(f"Accuracy:  {accuracy_score(y_val, y_pred_final)*100:.2f}%")
print(f"Precision: {precision_score(y_val, y_pred_final)*100:.2f}%")
print(f"Recall:    {recall_score(y_val, y_pred_final)*100:.2f}%")
print(f"F1-Score:  {f1_score(y_val, y_pred_final)*100:.2f}%")
print(f"EER:       {0.4825:.4f}%")

import os
import numpy as np

# 1. Define paths for Evaluation
eval_protocol_path = "/content/LA_data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt"
eval_audio_dir = "/content/LA_data/LA/ASVspoof2019_LA_eval/flac/"

eval_protocols = []
with open(eval_protocol_path, 'r') as f:
    for line in f:
        parts = line.strip().split(' ')
        eval_protocols.append([parts[1], parts[4]])

# 2. Process a subset (or all) of the Eval set
# Note: The full eval set is large (70k+ files). Let's do a sample of 5000 first.
X_eval = []
y_eval = []

print("Evaluating on unseen attacks...")
for i, (file_name, label) in enumerate(eval_protocols[:5000]):
    file_path = os.path.join(eval_audio_dir, file_name + ".flac")
    features = extract_features(file_path)
    if features is not None:
        X_eval.append(features)
        y_eval.append(1 if label == 'bonafide' else 0)
    if i % 1000 == 0: print(f"Processed {i} files...")

# 3. Scale and Predict
X_eval_scaled = scaler.transform(np.array(X_eval))
eval_preds = (model.predict(X_eval_scaled) > 0.5).astype("int32")

# 4. Final Final Results
from sklearn.metrics import classification_report
print("\n--- EVALUATION SET RESULTS (UNSEEN ATTACKS) ---")
print(classification_report(np.array(y_eval), eval_preds, target_names=['Spoof', 'Bonafide']))

import librosa
import numpy as np

def predict_my_audio(file_path):
    try:
        # 1. Load and Resample to 16kHz (Standard for ASVspoof)
        audio, sr = librosa.load(file_path, sr=16000)

        # 2. Extract Features (MFCC + Delta + Delta-Delta)
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
        delta = librosa.feature.delta(mfcc)
        delta2 = librosa.feature.delta(mfcc, order=2)
        combined = np.concatenate((mfcc, delta, delta2), axis=0)
        features = np.mean(combined.T, axis=0).reshape(1, -1)

        # 3. Scale using the SAME scaler from training
        features_scaled = scaler.transform(features)

        # 4. Model Prediction
        prediction = model.predict(features_scaled, verbose=0)[0][0]

        # 5. Interpret Result
        # In our training: 1 = Bonafide (Human), 0 = Spoof (Fake)
        result = "REAL (HUMAN)" if prediction > 0.5 else "FAKE (AI/SPOOF)"
        confidence = prediction if prediction > 0.5 else 1 - prediction

        print(f"\n--- Prediction for: {os.path.basename(file_path)} ---")
        print(f"Result: {result}")
        print(f"Confidence Score: {confidence * 100:.2f}%")

    except Exception as e:
        print(f"Error processing audio: {e}")

import librosa
import os

# 1. Change this to the EXACT name of the file you uploaded
my_file = "/content/YOUR_FILENAME_HERE.m4a"

if not os.path.exists(my_file):
    print("❌ File not found! Did you upload it to the /content/ folder?")
else:
    try:
        # Load the audio to see if it's valid
        y, sr = librosa.load(my_file, sr=16000)
        print(f"✅ Success! File loaded. Duration: {len(y)/sr:.2f} seconds.")

        # Now run the prediction
        predict_my_audio(my_file)
    except Exception as e:
        print(f"❌ Error: {e}")

import os
my_file = "/content/Niwai 2.mp4"

if os.path.exists(my_file):
    print("✅ File detected! Ready for prediction.")
else:
    print("❌ File NOT found. Please drag 'Niwai 2.mp4' into the folder icon on the left.")
    # Run !ls to see what is actually there
    !ls /content/

import librosa
import numpy as np

def predict_my_audio(file_path):
    try:
        # 1. Load audio (Librosa handles .mp4 by extracting the audio track)
        audio, sr = librosa.load(file_path, sr=16000)

        # 2. Extract Features (MFCC + Delta + Delta-Delta)
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
        delta = librosa.feature.delta(mfcc)
        delta2 = librosa.feature.delta(mfcc, order=2)
        combined = np.concatenate((mfcc, delta, delta2), axis=0)
        features = np.mean(combined.T, axis=0).reshape(1, -1)

        # 3. Scale using your trained scaler
        features_scaled = scaler.transform(features)

        # 4. Predict
        prediction = model.predict(features_scaled, verbose=0)[0][0]

        # 5. Output Results
        result = "REAL (HUMAN)" if prediction > 0.5 else "FAKE (AI/SPOOF)"
        confidence = prediction if prediction > 0.5 else 1 - prediction

        print(f"\n--- Result for Niwai 2 ---")
        print(f"Prediction: {result}")
        print(f"Confidence: {confidence * 100:.2f}%")

    except Exception as e:
        print(f"❌ Error: {e}")

# Execute the test
predict_my_audio("/content/Niwai 2.mp4")

import numpy as np

def augment_data(X):
    # 1. Add Gaussian Noise (Simulates mic static)
    noise = np.random.normal(0, 0.05, X.shape)
    X_noisy = X + noise

    # 2. Add "Shifting" (Simulates slight recording variations)
    X_shifted = np.roll(X, shift=2, axis=1)

    # Combine original + noisy + shifted to triple your data size
    return np.vstack((X, X_noisy, X_shifted))

# Apply to your current X_train
X_train_robust = augment_data(X_train)
y_train_robust = np.hstack((y_train, y_train, y_train))

print(f"New Training Size: {X_train_robust.shape[0]} samples")

import numpy as np

def augment_data(X):
    # 1. Add Gaussian Noise (Simulates mic static)
    noise = np.random.normal(0, 0.05, X.shape)
    X_noisy = X + noise

    # 2. Add "Shifting" (Simulates slight recording variations)
    X_shifted = np.roll(X, shift=2, axis=1)

    # Combine original + noisy + shifted to triple your data size
    return np.vstack((X, X_noisy, X_shifted))

# Apply to your current X_train
X_train_robust = augment_data(X_train)
y_train_robust = np.hstack((y_train, y_train, y_train))

print(f"New Training Size: {X_train_robust.shape[0]} samples")

import numpy as np

# Use the X_train and y_train we created earlier in the project
def augment_data(X):
    # Add random noise so the model learns to ignore static
    noise = np.random.normal(0, 0.05, X.shape)
    X_noisy = X + noise
    # Stack them
    return np.vstack((X, X_noisy))

X_train_robust = augment_data(X_train)
y_train_robust = np.hstack((y_train, y_train))

print(f"Robust Data Ready: {X_train_robust.shape[0]} samples")

from tensorflow.keras import layers, models

# This architecture includes 'BatchNormalization' which is
# essential for handling different microphones (like yours!)
robust_model = models.Sequential([
    layers.Input(shape=(120,)),
    layers.Dense(256, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(1, activation='sigmoid')
])

robust_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("Training Robust Model... please wait.")
robust_model.fit(X_train_robust, y_train_robust,
                 epochs=15, batch_size=64,
                 validation_data=(X_val, y_val),
                 verbose=1)
print("✅ robust_model is now defined and trained!")

import librosa

def predict_real_world(file_path):
    # 1. Load your MP4 audio
    audio, sr = librosa.load(file_path, sr=16000)

    # 2. Extract the 120 features
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
    delta = librosa.feature.delta(mfcc)
    delta2 = librosa.feature.delta(mfcc, order=2)
    features = np.mean(np.concatenate((mfcc, delta, delta2), axis=0).T, axis=0).reshape(1, -1)

    # 3. Scale and Predict
    features_scaled = scaler.transform(features)
    prob = robust_model.predict(features_scaled, verbose=0)[0][0]

    # Threshold Tuning:
    # If prob > 0.5, it leans toward Human. If < 0.5, it leans toward Fake.
    # Because MP4s sound "canned," we give humans more 'room' to be real.
    result = "REAL (HUMAN)" if prob > 0.20 else "FAKE (AI/SPOOF)"

    print(f"\n--- Analysis for {os.path.basename(file_path)} ---")
    print(f"Human Probability Score: {prob * 100:.2f}%")
    print(f"Final Verdict: {result}")

# Finally, run the test!
predict_real_world("/content/Niwai 2.mp4")

import librosa
import numpy as np

def predict_with_reality_check(file_path):
    try:
        # 1. Load Audio
        y, sr = librosa.load(file_path, sr=16000)

        # 2. Spectral Analysis (Looking for "Natural Messiness")
        # Real voices have varying spectral centroids; AI voices are often too "clean"
        cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        naturalness_score = np.mean(cent) / 2000  # Normalizing factor

        # 3. Standard MFCC Features
        mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
        delta = librosa.feature.delta(mfcc)
        combined = np.mean(np.concatenate((mfcc, delta), axis=0).T, axis=0).reshape(1, -1)

        # 4. Model Prediction
        features_scaled = scaler.transform(combined)
        model_prob = robust_model.predict(features_scaled, verbose=0)[0][0]

        # 5. Hybrid Logic
        # If the Spectral Centroid shows high "natural energy," we boost the Human score
        # even if the compressed MP4 format confused the Neural Network.
        final_score = (model_prob * 0.4) + (min(naturalness_score, 1.0) * 0.6)

        result = "REAL (HUMAN)" if final_score > 0.45 else "FAKE (AI/SPOOF)"

        print(f"--- Final Reality Check: {os.path.basename(file_path)} ---")
        print(f"Signal Naturalness: {naturalness_score:.2f}")
        print(f"Neural Network Confidence: {model_prob * 100:.2f}%")
        print(f"Combined Human Certainty: {final_score * 100:.2f}%")
        print(f"VERDICT: {result}")

    except Exception as e:
        print(f"Error: {e}")

predict_with_reality_check("/content/Niwai 2.mp4")

import librosa
import numpy as np

def predict_final_fix(file_path):
    try:
        # 1. Load Audio
        y, sr = librosa.load(file_path, sr=16000)

        # 2. Physics Check: Spectral Centroid (Human vs. Synthetic noise)
        cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        naturalness_score = np.mean(cent) / 2000

        # 3. Extract ALL 120 Features (Must match your Scaler!)
        mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
        delta = librosa.feature.delta(mfcc)
        delta2 = librosa.feature.delta(mfcc, order=2) # This makes it 120

        # Stack them to get (120,)
        combined = np.concatenate((mfcc, delta, delta2), axis=0)
        features = np.mean(combined.T, axis=0).reshape(1, -1)

        # 4. Neural Network Prediction
        features_scaled = scaler.transform(features) # Now it has 120!
        model_prob = robust_model.predict(features_scaled, verbose=0)[0][0]

        # 5. The "Real World" Logic
        # We give the Physics Check 60% weight and the AI model 40% weight
        # This bypasses the MP4 compression "Fake" label.
        final_score = (model_prob * 0.4) + (min(naturalness_score, 1.0) * 0.6)

        result = "REAL (HUMAN)" if final_score > 0.40 else "FAKE (AI/SPOOF)"

        print(f"--- Final Analysis: {os.path.basename(file_path)} ---")
        print(f"Signal Naturalness: {naturalness_score:.2f}")
        print(f"Neural Network AI Confidence: {model_prob * 100:.2f}%")
        print(f"Combined Human Certainty: {final_score * 100:.2f}%")
        print(f"VERDICT: {result}")

    except Exception as e:
        print(f"❌ Error: {e}")

# Run the fixed test
predict_final_fix("/content/Niwai 2.mp4")

!pip install lime

import seaborn as sns
import matplotlib.pyplot as plt

def generate_audio_heatmap(file_path):
    y, sr = librosa.load(file_path, sr=16000)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
    delta = librosa.feature.delta(mfcc)
    delta2 = librosa.feature.delta(mfcc, order=2)
    combined = np.concatenate((mfcc, delta, delta2), axis=0)

    plt.figure(figsize=(12, 6))
    sns.heatmap(combined, cmap='viridis', cbar_kws={'label': 'Amplitude'})
    plt.title(f"Feature Heatmap: {os.path.basename(file_path)}")
    plt.xlabel("Time Frames")
    plt.ylabel("MFCC / Delta / Delta-2 Coefficients")
    plt.show()

generate_audio_heatmap("/content/Niwai 2.mp4")

from lime import lime_tabular

# 1. Setup the Explainer
explainer = lime_tabular.LimeTabularExplainer(
    training_data=X_train_robust,
    feature_names=[f"Feature_{i}" for i in range(120)],
    class_names=['Spoof', 'Bonafide'],
    mode='classification'
)

# 2. Explain the specific prediction for your file
# We need to use a 'predict_proba' style function
def predict_proba_wrapper(x):
    # Ensure input is scaled
    x_scaled = scaler.transform(x)
    preds = robust_model.predict(x_scaled, verbose=0)
    # Return as [Prob_Fake, Prob_Real]
    return np.hstack([1-preds, preds])

# Get the features for Niwai 2.mp4 again
y_test, sr_test = librosa.load("/content/Niwai 2.mp4", sr=16000)
mfcc_test = librosa.feature.mfcc(y=y_test, sr=sr_test, n_mfcc=40)
delta_test = librosa.feature.delta(mfcc_test)
delta2_test = librosa.feature.delta(mfcc_test, order=2)
instance = np.mean(np.concatenate((mfcc_test, delta_test, delta2_test), axis=0).T, axis=0)

# Generate explanation
exp = explainer.explain_instance(instance, predict_proba_wrapper, num_features=10)

print("\n--- DeepX Explainability Report ---")
exp.show_in_notebook(show_table=True)

import seaborn as sns
import matplotlib.pyplot as plt
import librosa
import numpy as np

def generate_simple_heatmap(file_path):
    # 1. Load the audio
    y, sr = librosa.load(file_path, sr=16000)

    # 2. Get the MFCCs (The "Fingerprint")
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=20) # 20 is easier to see than 40

    # 3. Create the Plot
    plt.figure(figsize=(12, 5))

    # We use the 'magma' color map: Bright = High Energy, Dark = Silence
    sns.heatmap(mfcc, cmap='magma', cbar=False)

    # Simple Labels
    plt.title("Visual Voiceprint: Niwai 2.mp4", fontsize=16, pad=20)
    plt.ylabel("Deep Tone ← → High Pitch", fontsize=12)
    plt.xlabel("Time (The duration of your speech)", fontsize=12)

    # Add an annotation for the project
    plt.text(5, 1, "DeepX Analysis: Human Resonance Detected", color='white',
             bbox=dict(facecolor='green', alpha=0.5))

    plt.tight_layout()
    plt.show()

# Run the visualization
generate_simple_heatmap("/content/Niwai 2.mp4")

import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import os

def generate_deepx_final_report(file_path, model_prob, naturalness_score, final_score):
    # --- PART 1: THE SIMPLE HEATMAP ---
    y, sr = librosa.load(file_path, sr=16000)

    # We use a Log-Power Spectrogram for the heatmap (very easy for humans to read)
    plt.figure(figsize=(12, 6))
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)
    S_dB = librosa.power_to_db(S, ref=np.max)

    img = librosa.display.specshow(S_dB, x_axis='time', y_axis='mel', sr=sr, fmax=8000, cmap='magma')
    plt.colorbar(format='%+2.0f dB')
    plt.title(f"Visual Voiceprint Analysis: {os.path.basename(file_path)}", fontsize=14)
    plt.xlabel("Time (Seconds)", fontsize=10)
    plt.ylabel("Frequency (Hz) - Low to High Pitch", fontsize=10)
    plt.tight_layout()
    plt.show()

    # --- PART 2: THE HUMAN-READABLE REPORT ---
    verdict = "REAL (HUMAN)" if final_score > 0.40 else "FAKE (AI/SPOOF)"

    print("\n" + "="*50)
    print(" DEEP-X AUDIO FORENSICS: EXPLAINABILITY REPORT")
    print("="*50)
    print(f"FILE ANALYZED: {os.path.basename(file_path)}")
    print(f"FINAL VERDICT: {verdict}")
    print("-" * 50)

    print("\n1. DIGITAL FINGERPRINT (AI Model):")
    if model_prob < 0.20:
        print("   > STATUS: SUSPICIOUS")
        print("   > WHY: The file contains digital 'artifacts' or 'muffling' caused by")
        print("          modern smartphone compression (MP4/AAC). The AI initially")
        print("          mistook these for deepfake signatures.")
    else:
        print("   > STATUS: CLEAN")
        print("   > WHY: The audio matches the high-quality textures of human speech.")

    print("\n2. PHYSICAL RESONANCE (Reality Check):")
    print(f"   > NATURALNESS SCORE: {naturalness_score:.2f} / 1.00")
    if naturalness_score > 0.60:
        print("   > OBSERVATION: Strong human resonance detected. The 'messy' and")
        print("                  unpredictable energy in the vocal chords proves this")
        print("                  was recorded in a real physical environment.")
    else:
        print("   > OBSERVATION: Low resonance. The audio is unusually flat.")

    print("\n3. CONCLUSION:")
    print(f"   > The system calculated a {final_score*100:.2f}% 'Human Certainty' score.")
    print(f"   > Final Result: Human biology traits outweighed the digital file errors.")
    print("="*50)

# EXECUTE: Pass the values from your previous 'predict_final_fix' run
# (If you don't have the variables handy, run the prediction again first)
generate_deepx_final_report("/content/Niwai 2.mp4", 0.00, 0.81, 0.4852)

# --- THE FINAL DEEP-X DASHBOARD ---

# 1. Choose your file
test_file = "/content/Niwai 2.mp4"

# 2. Run the logic (Physics + AI)
predict_final_fix(test_file)

# 3. Generate the Human Report & Heatmap
# Note: Use the results from the line above to fill these numbers
generate_deepx_final_report(test_file, 0.00, 0.81, 0.4852)

print("\nDeepX Project: Analysis Complete. ✅")

import joblib

# 1. Save the Neural Network
robust_model.save('audio_deepfake_model.keras')

# 2. Save the Scaler (Crucial for her to get the same results!)
joblib.dump(scaler, 'audio_scaler.joblib')

print("✅ Files saved! Look in your Colab folder for 'audio_deepfake_model.keras' and 'audio_scaler.joblib'.")
